if(typeof CONTAM == "undefined")
{
  var CONTAM = {};
}

CONTAM.Icons = {};
CONTAM.Icons.FLOW_E   =  1; /* flow arrow - pointing east */
CONTAM.Icons.FLOW_W   =  2; /* flow arrow - pointing west */
CONTAM.Icons.FLOW_N   =  3; /* flow arrow - pointing north */
CONTAM.Icons.FLOW_S   =  4; /* flow arrow - pointing south */
CONTAM.Icons.ZONE_ST  =  5; /* zone - standard */
CONTAM.Icons.ZONE_PH  =  6; /* zone - phantom */
CONTAM.Icons.ZONE_AM  =  7; /* zone - ambient */
/*efine CONT_SS     8     CONTAMUIinant source/sink (C93) */
CONTAM.Icons.WL_EW    =  11; /* wall - east/west */
CONTAM.Icons.WL_NS    =  12; /* wall - north/south */
CONTAM.Icons.WL_ES    =  14; /* wall - northwest corner */
CONTAM.Icons.WL_SW    =  15; /* wall - northeast corner */
CONTAM.Icons.WL_NW    =  16; /* wall - southeast corner */
CONTAM.Icons.WL_NE    =  17; /* wall - southwest corner */
CONTAM.Icons.WL_NES   =  18; /* walls - to north, east, and south */
CONTAM.Icons.WL_ESW   =  19; /* walls - to east, south, and west */
CONTAM.Icons.WL_NSW   =  20; /* walls - to south, west, and north */
CONTAM.Icons.WL_NEW   =  21; /* walls - to west, north, and east */
CONTAM.Icons.WL_NESW  =  22; /* wall quad corner */
CONTAM.Icons.OPNG     =  23; /* opening - 1-way airflow */
CONTAM.Icons.DOOR     =  24; /* opening - 2-way airflow */
CONTAM.Icons.LG_OPNG  =  25; /* large 1-way opening */
CONTAM.Icons.LG_DOOR  =  27; /* large 2-way opening */
CONTAM.Icons.FAN_E    =  28; /* fan - flow to the east */
CONTAM.Icons.FAN_W    =  29; /* fan - flow to the west */
CONTAM.Icons.FAN_N    =  30; /* fan - flow to the north */
CONTAM.Icons.FAN_S    =  31; /* fan - flow to the south */
CONTAM.Icons.NOTE     =  42; /* note - '*' */
CONTAM.Icons.BOX_S    = 128; /* box - AHS supply */
CONTAM.Icons.BOX_R    = 129; /* box - AHS return */
CONTAM.Icons.S_AHS    = 130; /* simple AHS zones/element */
CONTAM.Icons.PEXP     = 131; /* personal exposure */
CONTAM.Icons.PERSON   = 132; /* personal activity (future) */
CONTAM.Icons.CONT_SS  = 133; /* CONTAMUIinant source/sink (C95) */
CONTAM.Icons.CONT_RX  = 134; /* CONTAMUIinant reaction (future) */
CONTAM.Icons.WMS_EW   = 136; /* mass layers - east/west, floor */
CONTAM.Icons.WMS_NS   = 137; /* mass layers - north/south */
CONTAM.Icons.WDW_EW   = 138; /* window layers - east/west, floor */
CONTAM.Icons.WDW_NS   = 139; /* window layers - north/south */
CONTAM.Icons.GEN_MASS = 140; /* generic zone mass */
CONTAM.Icons.RAD_INT  = 141; /* radiant interchange */
CONTAM.Icons.HEAT_SRC = 142; /* heat source */
CONTAM.Icons.DCT_EW   = 143; /* duct (not saved) - east/west */
CONTAM.Icons.DCT_NS   = 144; /* duct (not saved) - north/south */
CONTAM.Icons.DCT_EWk  = 145; /* duct (saved) - east/west */
CONTAM.Icons.DCT_NSk  = 146; /* duct (saved) - north/south */
CONTAM.Icons.DCT_ES   = 147; /* duct - east/south */
CONTAM.Icons.DCT_SW   = 148; /* duct - south/west */
CONTAM.Icons.DCT_NW   = 149; /* duct - north/west */
CONTAM.Icons.DCT_NE   = 150; /* duct - north/east */
CONTAM.Icons.DCT_X    = 151; /* duct crossing */
CONTAM.Icons.DCT_EWg  = 152; /* duct - east/west - grouping icon (future) */
CONTAM.Icons.DCT_NSg  = 153; /* duct - north/south - grouping icon (future) */
CONTAM.Icons.DCT_NSn  = 154; /* duct - north/south - north positive */
CONTAM.Icons.DCT_EWe  = 155; /* duct - east/west - east positive */
CONTAM.Icons.DCT_NSs  = 156; /* duct - north/south - south positive */
CONTAM.Icons.DCT_EWw  = 157; /* duct - east/west - west positive */
CONTAM.Icons.JCT      = 158; /* junction */
CONTAM.Icons.JCT_CA   = 159; /* junction - connected to level above */
CONTAM.Icons.JCT_CB   = 160; /* junction - connected to level below */
CONTAM.Icons.JCT_CAB  = 161; /* junction - connected above & below */
CONTAM.Icons.IOJ      = 162; /* junction terminal */
CONTAM.Icons.IOJ_CA   = 163; /* terminal - connected to level above */
CONTAM.Icons.IOJ_CB   = 164; /* terminal - connected to level below */
CONTAM.Icons.CL_EW    = 168; /* control link (not saved) - east/west */
CONTAM.Icons.CL_NS    = 169; /* control link (not saved) - north/south */
CONTAM.Icons.CL_EWk   = 170; /* control link (saved) - east/west */
CONTAM.Icons.CL_NSk   = 171; /* control link (saved) - north/south */
CONTAM.Icons.CL_ES    = 172; /* control link - east/south */
CONTAM.Icons.CL_SW    = 173; /* control link - south/west */
CONTAM.Icons.CL_NW    = 174; /* control link - north/west */
CONTAM.Icons.CL_NE    = 175; /* control link - north/east */
CONTAM.Icons.CL_X     = 176; /* control link - cross-over */
CONTAM.Icons.CA_N     = 177; /* control actuator - point to north */
CONTAM.Icons.CA_E     = 178; /* control actuator - point to east */
CONTAM.Icons.CA_S     = 179; /* control actuator - point to south */
CONTAM.Icons.CA_W     = 180; /* control actuator - point to west */
CONTAM.Icons.CS_N     = 181; /* control sensor - point to north */
CONTAM.Icons.CS_E     = 182; /* control sensor - point to east */
CONTAM.Icons.CS_S     = 183; /* control sensor - point to south */
CONTAM.Icons.CS_W     = 184; /* control sensor - point to west */
CONTAM.Icons.CTRLN    = 185; /* control node */
CONTAM.Icons.CTRLP    = 186; /* phantom control node */
CONTAM.Icons.CTRLS    = 187; /* super control node */
CONTAM.Icons.CTRLO    = 188; /* super element output control node */
CONTAM.Icons.CTRLI    = 189; /* super element input control node */
CONTAM.Icons.LT_E     = 206; /* Loop tail east */
CONTAM.Icons.LT_W     = 207; /* Loop tail west */
CONTAM.Icons.LT_N     = 208; /* Loop tail north */
CONTAM.Icons.LT_S     = 209; /* Loop tail south */
CONTAM.Icons.RADIO_Y  = 210; /* D2 322 box with dot inside */
CONTAM.Icons.RADIO_N  = 211; /* D3 323 empty box */
CONTAM.Icons.BUTTON   = 212; /* D4 324 pushbutton */
CONTAM.Icons.CHECK_L  = 213; /* D5 325 left side of check box */
CONTAM.Icons.CHECK_Y  = 214; /* D6 326 check box - yes */
CONTAM.Icons.CHECK_R  = 215; /* D7 327 right side of check box */
CONTAM.Icons.CHECK_N  = 216; /* D8 330 check box - no */
CONTAM.Icons.BLOCK    = 219; /* DB 333 full block   Û */
CONTAM.Icons.BLOCK_B  = 220; /* DC 334 bottom block Ü */
CONTAM.Icons.BLOCK_C  = 222; /* DE 335 center block   */
CONTAM.Icons.BLOCK_T  = 223; /* DF 336 top block    ß */
CONTAM.Icons.SIMGA    = 228; /* E4 344 Greek ä */
CONTAM.Icons.MU       = 230; /* E6 346 Greek æ */
CONTAM.Icons.OMEGA    = 234; /* EA 352 Greek omega */
CONTAM.Icons.DELTA    = 235; /* EB 353 Greek DELTA */
CONTAM.Icons.PLSMN    = 241; /* F1 361 ñ */
CONTAM.Icons.GTEQ     = 242; /* F2 362 ò */
CONTAM.Icons.LTEQ     = 243; /* F3 363 ó */
CONTAM.Icons.SUB_M    = 244; /* F4 364 subscript m */
CONTAM.Icons.SUB_N    = 245; /* F5 365 subscript n */
CONTAM.Icons.APPROX   = 247; /* F7 367 approx ÷ */
CONTAM.Icons.DEGRS    = 248; /* F8 370 degrees ø */
CONTAM.Icons.EXP_4    = 249; /* F9 371 exponent 4 */
CONTAM.Icons.EXP_3    = 250; /* FA 372 exponent 3 */
CONTAM.Icons.SQRT     = 251; /* FB 373 square root û */
CONTAM.Icons.EXP_N    = 252; /* FC 374 exponent n ü */
CONTAM.Icons.EXP_2    = 253; /* FD 375 exponent 2 ý */
CONTAM.Icons.SUB_2    = 254; /* FE 376 subscript 2 */
